/**
 * Embed code generation utilities
 */

import { generateShareUrl } from './shareUtils';

export type EmbedFormat = 'iframe' | 'html' | 'markdown';

/**
 * Generate iframe embed code
 */
export function generateIframeEmbed(
  code: string,
  width: number = 800,
  height: number = 600
): string {
  const shareUrl = generateShareUrl(code);
  return `<iframe
  src="${shareUrl}"
  width="${width}"
  height="${height}"
  frameborder="0"
  style="border: 1px solid #e5e7eb; border-radius: 8px;"
></iframe>`;
}

/**
 * Generate standalone HTML embed with Mermaid script
 */
export function generateHtmlEmbed(code: string): string {
  // Remove any init directives for clean embed
  const cleanCode = code.replace(/%%\{init:.*?\}%%\s*/gs, '').trim();

  return `<!-- Mermaid Diagram - Generated by forge Draw -->
<div class="mermaid">
${cleanCode}
</div>

<script type="module">
  import mermaid from 'https://esm.sh/mermaid@10.6.1';
  mermaid.initialize({ startOnLoad: true, theme: 'default' });
</script>`;
}

/**
 * Generate Markdown code block
 */
export function generateMarkdownEmbed(code: string): string {
  // Remove any init directives for clean embed
  const cleanCode = code.replace(/%%\{init:.*?\}%%\s*/gs, '').trim();

  return `\`\`\`mermaid
${cleanCode}
\`\`\``;
}

/**
 * Get all embed formats
 */
export function getAllEmbedFormats(code: string): Record<EmbedFormat, string> {
  return {
    iframe: generateIframeEmbed(code),
    html: generateHtmlEmbed(code),
    markdown: generateMarkdownEmbed(code),
  };
}
